import modals from "./modules/modals";
import toTop from "./modules/toTop";
import timer from "./modules/timer";
import sliders from "./modules/sliders";
import zoom from "./modules/zoom";
import calc from "./modules/calc";
import validate from "./modules/validate";
import sendForm from "./modules/sendForm";

modals();
toTop();
timer("23 may 2022 22:00");
sliders();
calc();
zoom();
validate();
sendForm({ formId: "form1", someElem: [{ type: "block", id: "calc-total" }] });
sendForm({ formId: "form2", someElem: [{ type: "block", id: "calc-total" }] });
sendForm({ formId: "form3", someElem: [{ type: "block", id: "calc-total" }] });
sendForm({ formId: "form4", someElem: [{ type: "block", id: "calc-total" }] });
